### ISSUE TITLE
Crimson Branch incorrect bounds

### ISSUE THREAD

**Issue by Kisutora** [buff0000n/dojocad#1]
The boundaries of Crimson Branch seem to be smaller/different shape in-game.
![Warframe x64_hEiIB6udwE](https://user-images.githubusercontent.com/22685232/71107905-abf08b00-21ca-11ea-8150-2c7d207d1121.png)
![firefox_M5vHCg7Gj9](https://user-images.githubusercontent.com/22685232/71107909-adba4e80-21ca-11ea-8c56-2749dae7a03c.png)

[Link to my dojo's second floor in the dojo builder](https://buff0000n.github.io/dojoarch/?m=ce,0,44,0,2_h3,0,-64,0,0_h2,0,0,0,0_hi,0,-128,0,0_gs,0,-176,0,0_h5,0,-224,0,0_gs,-48,-144,0,0_gs,-48,-112,0,0_gs,48,-144,0,0_gs,48,-112,0,0_gl,96,-144,0,1_gs,96,-96,0,0_gs,128,-96,0,0_gs,160,-96,0,0_cb,144,-144,0,2_cr,144,-176,0,0_du,96,-192,0,0_ce,28,-176,0,1_ce,-28,-176,0,3_oa,258,-96,0,1_dd,0,-384,0,0_lt,41,-208,0,1_lb,46,-240,0,1_lc,-48,-240,0,3_le,-46,-208,0,3&v=3,-131,427,0)

**Comment by buff0000n** [comment]
Son of a...  That kind of arrangement definitely didn't work when I tested it a month ago.  I need to retest the stupid bounds from scratch.

Thanks for the heads up!

**Comment by buff0000n** [comment]
In hindsight my testing process was probably incomplete.  Anyway, it should be fixed now.  Thanks!

**Comment by zaza7** [comment]
It appears the dimensions for the crimson branch are still incorrect as laying my dojo out tells me the crimson branch and the oracle lab are colliding when in fact in the game they do not. 
![😧🐣🍨🥀🗼⚙️](https://user-images.githubusercontent.com/4474031/83838062-2f912c00-a6c6-11ea-9592-20dd941cc158.png)
![🥦🥜📃🚑🌏🌪](https://user-images.githubusercontent.com/4474031/83838056-2c963b80-a6c6-11ea-89d0-f1ed76f69e32.png)

**Comment by buff0000n** [comment]
@zaza7 Thanks for the heads up.  

It's even worse than that.  This works in game:
<img width="341" alt="Screen Shot 2020-06-05 at 3 02 02 AM" src="https://user-images.githubusercontent.com/43117210/83852431-5efd6400-a6d9-11ea-9130-d0c20ff93f01.png">
And this works:
<img width="323" alt="Screen Shot 2020-06-05 at 3 02 17 AM" src="https://user-images.githubusercontent.com/43117210/83852450-66bd0880-a6d9-11ea-9db6-62c42295ce04.png">
But this doesn't:
<img width="322" alt="Screen Shot 2020-06-05 at 3 02 36 AM" src="https://user-images.githubusercontent.com/43117210/83852472-70467080-a6d9-11ea-92a1-c78b195f4f57.png">
Even though, as far as I can tell after re-re-testing, a small garden is the same depth as the Chem Lab and the same width as a T-Shaped connector.  Either there's a second, smaller notch inside the notch in the Crimson Branch's bounds, or the Chem Lab is 1 meter less deep.  Either of those is a frickin nightmare.

**Comment by buff0000n** [comment]
@zaza7 I ended up just resizing the notch in the Crimson Branch and lopping a meter off the Chem Lab.  Let me know if it fixes your issue.  Thanks!

**Comment by zaza7** [comment]
The collision issue with the layout I had has been fixed, thanks for the quick fix. 👍
